version: "3.8"
services:
    
    db:
        image: mysql
        container_name: db_foodomarket_mysql
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev_foodomarket
    
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_foodomarket
        restart: always
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
        networks:
            - dev_foodomarket
    
    mailer:
        image: schickling/mailcatcher
        container_name: mailer_foodomarket
        ports:
            - "1025:1025"
            - "8081:1080"
        networks:
            - dev_foodomarket
    
    www:
        image: www_php
        build: php
        container_name: www_foodomarket
        ports:
            - "8086:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ../:/var/www
        restart: always
        networks:
            - dev_foodomarket

networks:
    dev_foodomarket:

volumes:
    db-data:
